### ISSUE TITLE
The dynamic map doesn't show up reliably

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/Fivecircle#4]
The dynamic map on the User profile does not show up reliably. The issue is present in both local development and in production on Heroku, but the issue appears to be more frequent on Heroku. The issue may be related to needing to precompile JS assets for Heroku as Professor Kuhl laid out in class [and on Piazza](https://uiowa.instructure.com/courses/61301/external_tools/849).

**Comment by johnwmillr** [comment]
@hbwhite-edu and @Ahmed-Elmaleh, you can reference and close this issue when you create a PR for your `geoLocation` branch. Looks like it was commit af492717c61b72042899b2f0e643d108b2ad5979 that solved the issue.

**Comment by Ahmed-Elmaleh** [comment]
Ohhh

**Comment by johnwmillr** [comment]
Let's close the issue when you do a pull request. Technically the issue is still unresolved because we haven't merged the code to `master` yet. When you create the pull request you'll reference this issue by typing something like, "This fixes #4", and we'll see how it's all linked together.

**Comment by johnwmillr** [comment]
Fixed by #7
